server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://192.168.1.101:3306/test?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 1
  http:
    encoding:
      charset: utf-8
      enabled: true